[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*" # This is a common convention for functions
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/properties/:property_id/files"
  to = "/.netlify/functions/getFiles"
  status = 200
